name: tenzistore
description: TenziStore for businesses.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  badges: ^2.0.3
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  chopper: ^6.0.0
  flutter_mobx: ^2.0.6+5
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.9
  firebase_messaging: ^14.2.0
  flutter_share: ^2.0.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.1.0
  mobx: ^2.1.3
  share_plus: ^6.3.0
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  flutter_launcher_icons: ^0.11.0
  hive_generator: ^2.0.0
  mobx_codegen: ^2.1.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:


  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
